---

- name: "Install de-kde package group"
  include_role:
    name: common/install
  vars:
    packages: "{{ de_kde[ansible_distribution]['packages'] }}"


- block:
  # root

  - name: "Set locale to {{ lang }}"
    shell:
      cmd: "localectl set-locale LANG={{ lang }}"

  - name: "Disable ballo"
    shell:
      cmd: "baloctl disable"

  become: true
