---

- name: "Install base-wm package group"
  include_role:
    name: common/install
  vars:
    packages: "{{ wm_i3[ansible_distribution]packages }}"
    pip_packages: "{{ wm_i3[ansible_distribution]pip_packages }}"
