- name: Clone hyprland-protocols repository
  ansible.builtin.git:
    repo: https://github.com/hyprwm/hyprland-protocols
    dest: "{{ ansible_env.HOME }}/apps/HyprSources/hyprland-protocols"
    version: "{{ hyprland_protocols }}"
  register: git_clone_result

- name: Create build directory if not exists
  ansible.builtin.file:
    path: "/home/{{ username }}/apps/HyprSources/hyprland-protocols/build"
    state: directory

- name: Configure with meson
  ansible.builtin.command:
    cmd: meson setup --prefix=/usr --buildtype=release
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hyprland-protocols/build"

- name: Build with ninja
  ansible.builtin.command:
    cmd: ninja
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hyprland-protocols/build"
  register: build_result
  failed_when: build_result.rc != 0

- name: Install hyprland-protocols
  ansible.builtin.command:
    cmd: ninja install
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hyprland-protocols"
  become: true
  register: install_result
  failed_when: install_result.rc != 0
