---
- name: Configure Workstation
  hosts: all
  become: yes

  roles:
    - common

  tasks:
    - name: Include distribution-specific tasks for Arch Linux
      include_role:
        name: arch
      when: ansible_distribution == 'ArchLinux'

    - name: Include distribution-specific tasks for Ubuntu
      include_role:
        name: ubuntu
      when: ansible_distribution == 'Ubuntu'
