---
- name: Update package cache
  hosts: localhost
  tags: always
  become: true
  pre_tasks:

    - name: pre-run | update package cache (arch)
      tags: always
      pacman:
        update_cache: yes
        upgrade: yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt:
        update_cache: yes
        upgrade: yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install packages
  hosts: localhost
  become: true
  roles:
    - role: precondition
    - role: packages/apps
    - role: packages/bases
    - role: packages/breeze
    - role: packages/disk-monitoring
    - role: packages/docker
    - role: packages/font
    - role: packages/login-sddm
    - role: packages/thunar
    - role: packages/modern-unix
    - role: packages/wm-base
    - role: packages/wm-hyprland
    - role: packages/xorg
    - role: packages/zsh

- name: Install/Compile applications
  hosts: localhost
  roles:
    - role: manual/ssh
    - role: manual/git
    - role: manual/dotfiles
    - role: manual/dev-tools
    - role: manual/utils
    - role: manual/wm-hyprland
