#!/usr/bin/env bash

sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

ansible-galaxy install -r requirements.yml
ansible-playbook -i ./inventory/local.ini main.yml --ask-become-pass --ask-vault-pass
