---

- name: "Install vmware-guest package group"
  include_role:
    name: common/install
  vars:
    packages: "{{ vmware_guest[ansible_distribution]['packages'] }}"
    service: "{{ vmware_guest.service }}"

  become: true
