---
- block:
  # root
  - name: "Get user home stat"
    stat:
      path: "/home/{{ username }}"
    register: user_home

  - name: "Throw error if user home not exists"
    fail:
      msg: "/home/{{ username }} does not exists"
    when: not user_home.stat.exists

  - name: 'Install base packages'
    package:
      name:
        - openssl
        # - python-pip
        # - python-setuptools
        - rustup
      state: present

  - name: 'rustup install stable for {{ username }} user'
    shell: |
      rustup install stable
    become_user: "{{ username }}"

  - name: 'rustup set stable as default for {{ username }} user'
    shell: |
      rustup default stable
    become_user: "{{ username }}"

  become: true
