- name: Install mise
  command:
    cmd: cargo install mise

- name: Install bob
  command:
    cmd: cargo install bob-nvim

- name: Souce mise and bob
  command:
    cmd: source "{{ lookup('env', 'HOME') }}/.zshrc"

- name: Install neovim
  command:
    cmd: bob use nightly

- name: Install node
  command:
    cmd: mise use -g node@lts

- name: Install golang
  command:
    cmd: mise use -g go
