---

- name: "Install login-sddm package group"
  include_role:
    name: common/install
  vars:
    packages: "{{ login_sddm[ansible_distribution]['packages'] }}"

- name: "Copy sddm config"
  copy:
    src: "{{ role_path }}/files/sddm.conf"
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: '0755'
  become: true

- name: 'Enable sddm systemd service'
  systemd:
    name: 'sddm'
    enabled: 'yes'
  become: true
