---

- name: "Install login-sddm package group"
  include_role:
    name: common/install
  vars:
    packages: "{{ login_sddm.packages }}"

- name: "Install theme"
  git:
    repo: 'https://github.com/niki-on-github/simple-login-sddm-theme'
    dest: /usr/share/sddm/themes/simple-login
  become: true

- name: "Copy sddm config"
  copy:
    src: "{{ role_path }}/files/sddm.conf"
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: '0755'
  become: true

- name: 'Enable sddm systemd service'
  systemd:
    name: 'sddm'
    enabled: 'yes'
  become: true
