- name: Ensure Hyprland repository is cloned or updated
  git:
    repo: https://github.com/hyprwm/Hyprland.git
    version: "{{ hyprland }}"
    dest: "{{ ansible_env.HOME }}/apps/HyprSources/Hyprland"
    recursive: true
    force: true
  register: git_clone_result

- name: Replace /usr/local with /usr in Makefile
  lineinfile:
    path: "{{ ansible_env.HOME }}/apps/HyprSources/Hyprland/Makefile"
    regexp: '^([^#]*)(\/usr\/local)(.*)$'
    line: '\1/usr\3'

- name: Create build directory if not exists
  file:
    path: "{{ ansible_env.HOME }}/apps/HyprSources/Hyprland/build"
    state: directory

- name: Configure with meson
  command:
    cmd: meson setup --prefix=/usr --buildtype=release
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/Hyprland/build"

- name: Build with ninja
  command:
    cmd: ninja
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/Hyprland/build"
  register: build_result
  failed_when: build_result.rc != 0

- name: Install Hyprland
  command:
    cmd: ninja install
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/Hyprland/build"
  become: true
  register: install_result
  failed_when: install_result.rc != 0
