- name: Clone hypridle repository
  git:
    repo: https://github.com/hyprwm/hypridle.git
    dest: "{{ ansible_env.HOME }}/apps/HyprSources/hypridle"
    version: "{{ hypridle }}"
    recursive: yes
  register: git_clone_result

- name: Configure with CMake
  command:
    cmd: cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B ./build
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hypridle"
  register: configure_result
  failed_when: configure_result.rc != 0
  when: not git_clone_result.failed

- name: Build hypridle
  command:
    cmd: cmake --build ./build --config Release --target hypridle -j"{{ remote_cpu_cores }}"
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hypridle"
  register: build_result
  failed_when: build_result.rc != 0
  when: not git_clone_result.failed

- name: Install hypridle
  command:
    cmd: cmake --install ./build
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hypridle"
  become: true
  register: install_result
  failed_when: install_result.rc != 0
