- name: Clone hyprwayland-scanner repository
  git:
    repo: https://github.com/hyprwm/hyprwayland-scanner.git
    dest: "{{ ansible_env.HOME }}/apps/HyprSources/hyprwayland-scanner"
    version: "{{ hyprscan }}"
    recursive: yes
  register: git_clone_result

- name: Check if cloning was successful
  fail:
    msg: "Download failed for hyprwayland-scanner. Please check log."
  when: git_clone_result.failed

- name: Configure with CMake
  command:
    cmd: cmake -DCMAKE_INSTALL_PREFIX=/usr -B build
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hyprwayland-scanner"
  register: configure_result
  failed_when: configure_result.rc != 0
  when: not git_clone_result.failed

- name: Build hyprwayland-scanner
  command:
    cmd: cmake --build build -j"{{ remote_cpu_cores }}"
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hyprwayland-scanner"
  register: build_result
  failed_when: build_result.rc != 0
  when: not git_clone_result.failed

- name: Install hyprwayland-scanner
  command:
    cmd: cmake --install build
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/hyprwayland-scanner"
  become: true
  register: install_result
  failed_when: install_result.rc != 0
