- name: Clone rofi repository
  git:
    repo: https://github.com/lbonn/rofi.git
    dest: "{{ ansible_env.HOME }}/apps/HyprSources/rofi"

- name: Configure with meson
  command:
    cmd: meson setup build
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/rofi"

- name: Build with ninja
  command:
    cmd: ninja -C build
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/rofi"
  register: build_result
  failed_when: build_result.rc != 0

- name: Install rofi
  command:
    cmd: ninja -C build install
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/rofi"
  become: true
  register: install_result
  failed_when: install_result.rc != 0
