- name: Clone xdg-desktop-portal-hyprland repository
  git:
    repo: https://github.com/hyprwm/xdg-desktop-portal-hyprland.git
    dest: "{{ ansible_env.HOME }}/apps/HyprSources/xdg-desktop-portal-hyprland"
    version: "{{ xdg_desktop_portal_hyprland }}"
    recursive: yes
  register: git_clone_result

- name: Configure with CMake
  command:
    cmd: cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBEXECDIR:PATH=/usr/lib -S . -B ./build
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/xdg-desktop-portal-hyprland"
  register: configure_result
  failed_when: configure_result.rc != 0

- name: Build with CMake
  command:
    cmd: cmake --build ./build --config Release --target all -j"{{ remote_cpu_cores }}"
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/xdg-desktop-portal-hyprland"
  register: build_result
  failed_when: build_result.rc != 0

- name: Install xdg-desktop-portal-hyprland
  command:
    cmd: cmake --install ./build
    chdir: "{{ ansible_env.HOME }}/apps/HyprSources/xdg-desktop-portal-hyprland"
  become: true
  register: install_result
  failed_when: install_result.rc != 0
