---

- name: "Install de-xfce package group"
  include_role:
    name: common/install
  vars:
    packages: "{{ de_xfce.packages }}"
    services: "{{ de_xfce.services }}"


- name: "Set locale to {{ lang }}"
  shell:
    cmd: "localectl set-locale LANG={{ lang }}"
  become: true
