---

- name: "Install de-xfce package group"
  include_role:
    name: common/install
  vars:
    packages: "{{ de_xfce[ansible_distribution]['packages'] }}"
    services: "{{ de_xfce[ansible_distribution]['services'] }}"


- name: "Set locale to {{ lang }}"
  shell:
    cmd: "localectl set-locale LANG={{ lang }}"
  become: true
